services:
  - docker

before_install:
  - docker build -t anitbibin1202/multi-test -f ./client

script:
  - docker run anitbibin1202/multi-test

after_install:
  - docker build -t anitbibin1202/multi-client -f ./client
  - docker build -t anitbibin1202/multi-server -f ./server
  - docker build -t anitbibin1202/multi-worker -f ./worker    
  - docker build -t anitbibin1202/multi-client -f ./client  